### ISSUE TITLE
Add: Install Git

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPatternTemplate#9]
- [x] Read [Installing and Configuring Git](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/InstallingGit/InstallingGit.md)
- [x] Install Git
- [x] Close this issue

**Comment by kmohr-soprasteria** [comment]
reviewed doc, omitted installation (had git already installed before)
